---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  LABELS_CONFIG_FILE: '{{.ROOT_DIR}}/.github/labels.yaml'

tasks:

  append-app-labels:
    desc: Append container labels to the labels config file
    cmds:
      - for: { var: apps }
        cmd: |
          yq -i '. += [{"name": "app/{{.ITEM}}", "color": "0e8a16"}]' {{.LABELS_CONFIG_FILE}}
    vars:
      apps:
        sh: for dir in {{.ROOT_DIR}}/apps/*/; do basename "${dir}"; done
    preconditions:
      - msg: must only be run in a GH workflow
        sh: test -d /home/runner
